services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      # args:
      #   arg_pm2_pk: ${PM2_PUBLIC_KEY}
      #   arg_pm2_sk: ${PM2_SECRET_KEY}
    volumes:
      - ".local:/home/build/fullstack/.local"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    network_mode: bridge
    ports:
      - "3443:3443"
      - "4173:4173"
    stdin_open: true
    tty: true
    restart: always
    image: fullstack_image
    container_name: fullstack_container
